/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyPL {
  'id' : bigint,
  'totalProfitLoss' : number,
  'date' : string,
  'createdAt' : bigint,
  'headBalances' : Array<HeadBalance>,
}
export interface FixedDeposit {
  'id' : bigint,
  'customerName' : string,
  'closureDate' : string,
  'fdAmount' : number,
  'maturityDepositDate' : string,
  'createdAt' : bigint,
  'openingDate' : string,
  'cifNumber' : string,
  'interestRate' : number,
  'contactNumber' : string,
  'accountNumber' : string,
  'maturityAmount' : number,
  'tenure' : bigint,
  'interestAmount' : number,
}
export interface HeadBalance {
  'headName' : string,
  'profitLoss' : number,
  'closingBalance' : number,
  'openingBalance' : number,
  'headId' : bigint,
}
export interface PaymentHead {
  'id' : bigint,
  'headType' : string,
  'name' : string,
  'isDefault' : boolean,
}
export interface Transaction {
  'id' : bigint,
  'remark' : string,
  'status' : string,
  'transactionDate' : string,
  'frequencyType' : string,
  'transactionType' : string,
  'ifscCode' : string,
  'createdAt' : bigint,
  'accountHolderName' : string,
  'referenceId' : string,
  'bankName' : string,
  'accountNumber' : string,
  'amount' : number,
}
export interface _SERVICE {
  'addFixedDeposit' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      bigint,
      number,
      number,
      number,
      string,
      string,
    ],
    bigint
  >,
  'addPaymentHead' : ActorMethod<[string, string], bigint>,
  'addTransaction' : ActorMethod<[Transaction], bigint>,
  'deleteFixedDeposit' : ActorMethod<[bigint], undefined>,
  'deletePaymentHead' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'editPaymentHead' : ActorMethod<[bigint, string, string], undefined>,
  'getAllDailyPLs' : ActorMethod<[], Array<DailyPL>>,
  'getAllFixedDeposits' : ActorMethod<[], Array<FixedDeposit>>,
  'getAllPaymentHeads' : ActorMethod<[], Array<PaymentHead>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getDailyPLByDateRange' : ActorMethod<[string, string], Array<DailyPL>>,
  'getTransactionsByTypeAndStatus' : ActorMethod<
    [string, string],
    Array<Transaction>
  >,
  'saveDailyPL' : ActorMethod<[string, Array<HeadBalance>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];