/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'complaintNo' : string,
  'accountNo' : string,
  'createdAt' : bigint,
  'aadharNo' : string,
  'contactNo' : string,
  'panNo' : string,
  'dateOfComplaint' : string,
  'complaintBrief' : string,
}
export interface DailyPL {
  'id' : bigint,
  'totalProfitLoss' : number,
  'date' : string,
  'createdAt' : bigint,
  'headBalances' : Array<HeadBalance>,
}
export interface FixedDeposit {
  'id' : bigint,
  'customerName' : string,
  'closureDate' : string,
  'fdAmount' : number,
  'maturityDepositDate' : string,
  'createdAt' : bigint,
  'openingDate' : string,
  'cifNumber' : string,
  'interestRate' : number,
  'contactNumber' : string,
  'accountNumber' : string,
  'maturityAmount' : number,
  'tenure' : bigint,
  'interestAmount' : number,
}
export interface HeadBalance {
  'headName' : string,
  'profitLoss' : number,
  'closingBalance' : number,
  'openingBalance' : number,
  'headId' : bigint,
}
export interface InventoryProduct {
  'id' : bigint,
  'sku' : string,
  'reorderPoint' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'barcode' : string,
  'quantity' : bigint,
  'category' : string,
  'salePrice' : number,
  'unitCost' : number,
}
export interface Loan {
  'id' : bigint,
  'loanStartDate' : string,
  'customerName' : string,
  'loanAmount' : number,
  'dateOfBirth' : string,
  'createdAt' : bigint,
  'fatherHusbandName' : string,
  'totalInterestAmount' : number,
  'interestRate' : number,
  'nomineeName' : string,
  'loanTenureMonths' : bigint,
  'repaymentType' : string,
  'contactNo' : string,
  'fullAddress' : string,
}
export interface PaymentHead {
  'id' : bigint,
  'headType' : string,
  'name' : string,
  'isDefault' : boolean,
}
export interface StockTransaction {
  'id' : bigint,
  'transactionDate' : string,
  'transactionType' : string,
  'quantityChange' : bigint,
  'note' : string,
  'createdAt' : bigint,
  'productId' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'remark' : string,
  'status' : string,
  'transactionDate' : string,
  'frequencyType' : string,
  'transactionType' : string,
  'ifscCode' : string,
  'createdAt' : bigint,
  'accountHolderName' : string,
  'referenceId' : string,
  'bankName' : string,
  'accountNumber' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComplaint' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    bigint
  >,
  'addFixedDeposit' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      bigint,
      number,
      number,
      number,
      string,
      string,
    ],
    bigint
  >,
  'addLoan' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      number,
      bigint,
      string,
    ],
    bigint
  >,
  'addPaymentHead' : ActorMethod<[string, string], bigint>,
  'addProduct' : ActorMethod<
    [string, string, string, string, string, bigint, number, number, bigint],
    bigint
  >,
  'addStockTransaction' : ActorMethod<
    [bigint, string, bigint, string, string],
    bigint
  >,
  'addTransaction' : ActorMethod<[Transaction], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateProducts' : ActorMethod<
    [Array<bigint>, Array<number>, Array<number>, Array<bigint>],
    undefined
  >,
  'deleteComplaint' : ActorMethod<[bigint], undefined>,
  'deleteDailyPL' : ActorMethod<[bigint], undefined>,
  'deleteFixedDeposit' : ActorMethod<[bigint], undefined>,
  'deleteLoan' : ActorMethod<[bigint], undefined>,
  'deletePaymentHead' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'editPaymentHead' : ActorMethod<[bigint, string, string], undefined>,
  'editProduct' : ActorMethod<
    [bigint, string, string, string, string, string, number, number, bigint],
    undefined
  >,
  'getAllComplaints' : ActorMethod<[], Array<Complaint>>,
  'getAllDailyPLs' : ActorMethod<[], Array<DailyPL>>,
  'getAllFixedDeposits' : ActorMethod<[], Array<FixedDeposit>>,
  'getAllLoans' : ActorMethod<[], Array<Loan>>,
  'getAllPaymentHeads' : ActorMethod<[], Array<PaymentHead>>,
  'getAllProducts' : ActorMethod<[], Array<InventoryProduct>>,
  'getAllStockTransactions' : ActorMethod<[], Array<StockTransaction>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaintsByStatus' : ActorMethod<[string], Array<Complaint>>,
  'getDailyPLByDateRange' : ActorMethod<[string, string], Array<DailyPL>>,
  'getLoanById' : ActorMethod<[bigint], [] | [Loan]>,
  'getStockTransactionsByProduct' : ActorMethod<
    [bigint],
    Array<StockTransaction>
  >,
  'getTodayStockTransactions' : ActorMethod<[string], Array<StockTransaction>>,
  'getTransactionsByTypeAndStatus' : ActorMethod<
    [string, string],
    Array<Transaction>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyPL' : ActorMethod<[string, Array<HeadBalance>], bigint>,
  'updateComplaint' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateComplaintStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];