/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'remark' : IDL.Text,
  'status' : IDL.Text,
  'transactionDate' : IDL.Text,
  'frequencyType' : IDL.Text,
  'transactionType' : IDL.Text,
  'ifscCode' : IDL.Text,
  'createdAt' : IDL.Int,
  'accountHolderName' : IDL.Text,
  'referenceId' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
  'amount' : IDL.Float64,
});
export const HeadBalance = IDL.Record({
  'headName' : IDL.Text,
  'profitLoss' : IDL.Float64,
  'closingBalance' : IDL.Float64,
  'openingBalance' : IDL.Float64,
  'headId' : IDL.Nat,
});
export const DailyPL = IDL.Record({
  'id' : IDL.Nat,
  'totalProfitLoss' : IDL.Float64,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'headBalances' : IDL.Vec(HeadBalance),
});
export const FixedDeposit = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'closureDate' : IDL.Text,
  'fdAmount' : IDL.Float64,
  'maturityDepositDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'openingDate' : IDL.Text,
  'cifNumber' : IDL.Text,
  'interestRate' : IDL.Float64,
  'contactNumber' : IDL.Text,
  'accountNumber' : IDL.Text,
  'maturityAmount' : IDL.Float64,
  'tenure' : IDL.Nat,
  'interestAmount' : IDL.Float64,
});
export const PaymentHead = IDL.Record({
  'id' : IDL.Nat,
  'headType' : IDL.Text,
  'name' : IDL.Text,
  'isDefault' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addFixedDeposit' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addPaymentHead' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
  'deleteDailyPL' : IDL.Func([IDL.Nat], [], []),
  'deleteFixedDeposit' : IDL.Func([IDL.Nat], [], []),
  'deletePaymentHead' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'editPaymentHead' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'getAllDailyPLs' : IDL.Func([], [IDL.Vec(DailyPL)], ['query']),
  'getAllFixedDeposits' : IDL.Func([], [IDL.Vec(FixedDeposit)], ['query']),
  'getAllPaymentHeads' : IDL.Func([], [IDL.Vec(PaymentHead)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getDailyPLByDateRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DailyPL)],
      ['query'],
    ),
  'getTransactionsByTypeAndStatus' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'saveDailyPL' : IDL.Func([IDL.Text, IDL.Vec(HeadBalance)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'remark' : IDL.Text,
    'status' : IDL.Text,
    'transactionDate' : IDL.Text,
    'frequencyType' : IDL.Text,
    'transactionType' : IDL.Text,
    'ifscCode' : IDL.Text,
    'createdAt' : IDL.Int,
    'accountHolderName' : IDL.Text,
    'referenceId' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const HeadBalance = IDL.Record({
    'headName' : IDL.Text,
    'profitLoss' : IDL.Float64,
    'closingBalance' : IDL.Float64,
    'openingBalance' : IDL.Float64,
    'headId' : IDL.Nat,
  });
  const DailyPL = IDL.Record({
    'id' : IDL.Nat,
    'totalProfitLoss' : IDL.Float64,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'headBalances' : IDL.Vec(HeadBalance),
  });
  const FixedDeposit = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'closureDate' : IDL.Text,
    'fdAmount' : IDL.Float64,
    'maturityDepositDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'openingDate' : IDL.Text,
    'cifNumber' : IDL.Text,
    'interestRate' : IDL.Float64,
    'contactNumber' : IDL.Text,
    'accountNumber' : IDL.Text,
    'maturityAmount' : IDL.Float64,
    'tenure' : IDL.Nat,
    'interestAmount' : IDL.Float64,
  });
  const PaymentHead = IDL.Record({
    'id' : IDL.Nat,
    'headType' : IDL.Text,
    'name' : IDL.Text,
    'isDefault' : IDL.Bool,
  });
  
  return IDL.Service({
    'addFixedDeposit' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addPaymentHead' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
    'deleteDailyPL' : IDL.Func([IDL.Nat], [], []),
    'deleteFixedDeposit' : IDL.Func([IDL.Nat], [], []),
    'deletePaymentHead' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'editPaymentHead' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'getAllDailyPLs' : IDL.Func([], [IDL.Vec(DailyPL)], ['query']),
    'getAllFixedDeposits' : IDL.Func([], [IDL.Vec(FixedDeposit)], ['query']),
    'getAllPaymentHeads' : IDL.Func([], [IDL.Vec(PaymentHead)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getDailyPLByDateRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DailyPL)],
        ['query'],
      ),
    'getTransactionsByTypeAndStatus' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'saveDailyPL' : IDL.Func([IDL.Text, IDL.Vec(HeadBalance)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };
